# Generated by Django 5.2.8 on 2026-07-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
